//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.15 at 08:07:47 PM CST 
//


package inventariojeans;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class Ventas 
{

	String id_cliente;
	String total;
	String nombre_cliente;
	String id_vendedor;
	ArrayList <Items> contacts = new ArrayList <Items> ();
	
	static String saludo;
	

	public static void getIDCliente()
	{
		
	}
}

class Items
{
	String id_articulo;
	String descripcion;
	String cantidad;
	String precio;
	String importe;
	
}